/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.vistas;

import hotel.modelo.Conexion;
import hotel.modelo.Habitacion;
import hotel.modelo.HabitacionData;
import hotel.modelo.Huesped;
import hotel.modelo.Reservas;
import hotel.modelo.ReservasData;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author clara
 */

public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    private Conexion conexion;
    private ReservasData reservasData;
    private HabitacionData habitacionData;

    public Inicio() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH); // Maximiza Ventana
        try {
            conexion = new Conexion();
            reservasData = new ReservasData(conexion);

            // Cambia estado a las reservas y habitaciones,
            // cuando la fecha checkOut coincide con la actual o
            // ya ha caducado.

            cambiarEstadoHabitaciones();
 
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        menuPrincipal = new javax.swing.JMenuBar();
        submenuArchivo = new javax.swing.JMenu();
        itemSalir = new javax.swing.JMenuItem();
        submenuHuespedes = new javax.swing.JMenu();
        itemHuespedes = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        submenuHabitaciones = new javax.swing.JMenu();
        itemHabitaciones = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        itemTiposHabitaciones = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemListadoHabitaciones = new javax.swing.JMenuItem();
        submenuReservas = new javax.swing.JMenu();
        itemReservas = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        submenuConsultas = new javax.swing.JMenu();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(65, 105, 160));
        escritorio.setPreferredSize(new java.awt.Dimension(800, 577));
        escritorio.setLayout(null);

        menuPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        menuPrincipal.setMaximumSize(new java.awt.Dimension(546, 32771));
        menuPrincipal.setPreferredSize(new java.awt.Dimension(546, 40));

        submenuArchivo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/folder-1.png"))); // NOI18N
        submenuArchivo.setText("  Archivo");
        submenuArchivo.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        submenuArchivo.setPreferredSize(new java.awt.Dimension(120, 21));

        itemSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/cancel.png"))); // NOI18N
        itemSalir.setText("  Salir");
        itemSalir.setMaximumSize(new java.awt.Dimension(400, 100));
        itemSalir.setPreferredSize(new java.awt.Dimension(97, 50));
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        submenuArchivo.add(itemSalir);

        menuPrincipal.add(submenuArchivo);

        submenuHuespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/user-menu.png"))); // NOI18N
        submenuHuespedes.setText("  Huéspedes");
        submenuHuespedes.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        submenuHuespedes.setMaximumSize(new java.awt.Dimension(150, 32767));
        submenuHuespedes.setPreferredSize(new java.awt.Dimension(170, 21));

        itemHuespedes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/id-card.png"))); // NOI18N
        itemHuespedes.setText("  Formulario de huéspedes");
        itemHuespedes.setPreferredSize(new java.awt.Dimension(242, 50));
        itemHuespedes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHuespedesActionPerformed(evt);
            }
        });
        submenuHuespedes.add(itemHuespedes);
        submenuHuespedes.add(jSeparator2);

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/list-8.png"))); // NOI18N
        jMenuItem1.setText("  Listado de huéspedes");
        jMenuItem1.setPreferredSize(new java.awt.Dimension(195, 50));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        submenuHuespedes.add(jMenuItem1);

        menuPrincipal.add(submenuHuespedes);

        submenuHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/bank.png"))); // NOI18N
        submenuHabitaciones.setText("  Habitaciones");
        submenuHabitaciones.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        submenuHabitaciones.setMaximumSize(new java.awt.Dimension(150, 32767));

        itemHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/calendar-29.png"))); // NOI18N
        itemHabitaciones.setText("  Formulario de habitaciones");
        itemHabitaciones.setPreferredSize(new java.awt.Dimension(255, 50));
        itemHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemHabitacionesActionPerformed(evt);
            }
        });
        submenuHabitaciones.add(itemHabitaciones);
        submenuHabitaciones.add(jSeparator4);

        itemTiposHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/hierarchical-structure.png"))); // NOI18N
        itemTiposHabitaciones.setText("  Tipos de habitaciones");
        itemTiposHabitaciones.setPreferredSize(new java.awt.Dimension(314, 50));
        itemTiposHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTiposHabitacionesActionPerformed(evt);
            }
        });
        submenuHabitaciones.add(itemTiposHabitaciones);
        submenuHabitaciones.add(jSeparator1);

        itemListadoHabitaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/list-8.png"))); // NOI18N
        itemListadoHabitaciones.setText("  Listado de habitaciones");
        itemListadoHabitaciones.setPreferredSize(new java.awt.Dimension(228, 50));
        itemListadoHabitaciones.setRolloverEnabled(true);
        itemListadoHabitaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListadoHabitacionesActionPerformed(evt);
            }
        });
        submenuHabitaciones.add(itemListadoHabitaciones);

        menuPrincipal.add(submenuHabitaciones);

        submenuReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/star.png"))); // NOI18N
        submenuReservas.setText("  Reservas");
        submenuReservas.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        submenuReservas.setMaximumSize(new java.awt.Dimension(130, 32767));

        itemReservas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/calendar-39.png"))); // NOI18N
        itemReservas.setText("  Hacer una reserva");
        itemReservas.setActionCommand("Hacer reservas");
        itemReservas.setPreferredSize(new java.awt.Dimension(190, 50));
        itemReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemReservasActionPerformed(evt);
            }
        });
        submenuReservas.add(itemReservas);
        submenuReservas.add(jSeparator3);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/list-5.png"))); // NOI18N
        jMenuItem3.setText("  Listado de reservas");
        jMenuItem3.setPreferredSize(new java.awt.Dimension(178, 50));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        submenuReservas.add(jMenuItem3);

        menuPrincipal.add(submenuReservas);

        submenuConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/settings-3.png"))); // NOI18N
        submenuConsultas.setText("  Configuraciones");
        submenuConsultas.setActionCommand("Configuraciones");
        submenuConsultas.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        submenuConsultas.setInheritsPopupMenu(true);
        menuPrincipal.add(submenuConsultas);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHabitacionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHabitacion formularioHabitacion = new VistaHabitacion();
        Dimension ventana = formularioHabitacion.getSize();
        formularioHabitacion.setLocation((int)centrarVentanas(ventana).getWidth(),(int)centrarVentanas(ventana).getHeight());
        formularioHabitacion.setVisible(true);
        escritorio.add(formularioHabitacion);
        escritorio.moveToFront(formularioHabitacion);
    }//GEN-LAST:event_itemHabitacionesActionPerformed

    private void itemHuespedesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemHuespedesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHuesped formularioHuesped = new VistaHuesped();
        Dimension ventana = formularioHuesped.getSize();
        formularioHuesped.setLocation((int)centrarVentanas(ventana).getWidth(),(int)centrarVentanas(ventana).getHeight());
        formularioHuesped.setVisible(true);
        escritorio.add(formularioHuesped);
        escritorio.moveToFront(formularioHuesped);
    }//GEN-LAST:event_itemHuespedesActionPerformed

    private void itemReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemReservasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaReservas formularioReservas = new VistaReservas();
        Dimension ventana = formularioReservas.getSize();
        formularioReservas.setLocation((int)centrarVentanas(ventana).getWidth(),(int)centrarVentanas(ventana).getHeight());
        formularioReservas.setVisible(true);
        escritorio.add(formularioReservas);
        escritorio.moveToFront(formularioReservas);
    }//GEN-LAST:event_itemReservasActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void itemListadoHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListadoHabitacionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHabitacionesLista formularioHabitaciones = new VistaHabitacionesLista();
        Dimension ventana = formularioHabitaciones.getSize();
        formularioHabitaciones.setLocation((int)centrarVentanas(ventana).getWidth(),(int)centrarVentanas(ventana).getHeight());
        formularioHabitaciones.setVisible(true);
        escritorio.add(formularioHabitaciones);
        escritorio.moveToFront(formularioHabitaciones);
    }//GEN-LAST:event_itemListadoHabitacionesActionPerformed

    private void itemTiposHabitacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTiposHabitacionesActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaTiposHabitaciones formularioTipoHabitaciones = new VistaTiposHabitaciones();
        Dimension ventana = formularioTipoHabitaciones.getSize();
        formularioTipoHabitaciones.setLocation((int)centrarVentanas(ventana).getWidth(),(int)centrarVentanas(ventana).getHeight());
        formularioTipoHabitaciones.setVisible(true);
        escritorio.add(formularioTipoHabitaciones);
        escritorio.moveToFront(formularioTipoHabitaciones);    }//GEN-LAST:event_itemTiposHabitacionesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaHuespedesLista formularioHuespedesLista = new VistaHuespedesLista();
        Dimension ventana = formularioHuespedesLista.getSize();
        formularioHuespedesLista.setLocation((int)centrarVentanas(ventana).getWidth(),(int)centrarVentanas(ventana).getHeight());
        formularioHuespedesLista.setVisible(true);
        escritorio.add(formularioHuespedesLista);
        escritorio.moveToFront(formularioHuespedesLista);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        VistaReservasLista formularioReservasLista = new VistaReservasLista();
        Dimension ventana = formularioReservasLista.getSize();
        formularioReservasLista.setLocation((int)centrarVentanas(ventana).getWidth(),(int)centrarVentanas(ventana).getHeight());
        formularioReservasLista.setVisible(true);
        escritorio.add(formularioReservasLista);
        escritorio.moveToFront(formularioReservasLista);    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void cambiarEstadoHabitaciones(){
        
        if(!reservasData.buscaReservasAFinalizar().isEmpty()){
            
            int resp = JOptionPane.showConfirmDialog(null, "Hay "+reservasData.buscaReservasAFinalizar().size()+ "reserva/s que finaliza/n el día de hoy o ya finalizaron, desea desactivarla/s ahora ?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp != 1) {
            reservasData.buscaReservasAFinalizar().forEach(reservas -> {
            Habitacion habitacion = new Habitacion();
            Huesped huesped = new Huesped();
            habitacion.setHabitacionId(reservas.getHabitacionId().getHabitacionId());
            huesped.setHuespedId(reservas.getHuespedId().getHuespedId());

            reservasData.finReserva(habitacion, huesped);
            System.out.println("Reserva Número: " + reservas.getReservasId()
                    + " Habitacion id " + reservas.getHabitacionId().getHabitacionId()
                    + " Huesped : " + reservas.getHuespedId().getHuespedId());
            });

            JOptionPane.showMessageDialog(null, "Las reservas han sido desactivadas, verifique en la sección listado de reservas");
            } else if (resp != 2) {
                JOptionPane.showMessageDialog(null, "Acción cancelada, verifique la sección listado de reservas");
            }
        }
    }

    private Dimension centrarVentanas(Dimension ventana){
        Dimension values;
        values = new Dimension();
        Dimension pantalla = escritorio.getSize();
        values.setSize((pantalla.getWidth() - ventana.getWidth())/2, (pantalla.getHeight()- ventana.getHeight())/ 2);
        return values;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

        Conexion connection;
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem itemHabitaciones;
    private javax.swing.JMenuItem itemHuespedes;
    private javax.swing.JMenuItem itemListadoHabitaciones;
    private javax.swing.JMenuItem itemReservas;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemTiposHabitaciones;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JMenu submenuArchivo;
    private javax.swing.JMenu submenuConsultas;
    private javax.swing.JMenu submenuHabitaciones;
    private javax.swing.JMenu submenuHuespedes;
    private javax.swing.JMenu submenuReservas;
    // End of variables declaration//GEN-END:variables
}
