/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.vistas;

import static java.util.Collections.list;
import javax.swing.JTextField;

/**
 *
 * @author clara
 */

public class VistaHabitacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaHabitacion
     */
    public VistaHabitacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        textTitleDatosHabitacion = new javax.swing.JLabel();
        textHabitacionId = new javax.swing.JLabel();
        habitacionId = new javax.swing.JTextField();
        habitacionTipo = new javax.swing.JComboBox<>();
        textHabitacionEstado = new javax.swing.JLabel();
        textHabitacionTipoCama = new javax.swing.JLabel();
        textHabitacionTipo = new javax.swing.JLabel();
        habitacionBuscar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        habitacionTipoCama = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        habitacionGuardar = new javax.swing.JButton();
        habitacionEditar = new javax.swing.JButton();
        habitacionLimpiar = new javax.swing.JButton();
        habitacionBorrar = new javax.swing.JButton();
        habitacionEstadoLibre = new javax.swing.JRadioButton();
        habitacionEstadoOcupada = new javax.swing.JRadioButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        textTitleDatosHabitacion.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        textTitleDatosHabitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/calendar-29.png"))); // NOI18N
        textTitleDatosHabitacion.setText("DATOS HABITACIÓN");

        textHabitacionId.setText("N° HABITACIÓN");

        habitacionId.setToolTipText("Dejar este campo en blanco si desea cargar una nueva habitación");
        habitacionId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionIdActionPerformed(evt);
            }
        });

        habitacionTipo.setEditable(true);
        habitacionTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Item 2", "Item 3", "Item 4" }));

        textHabitacionEstado.setText("ESTADO");

        textHabitacionTipoCama.setText("TIPOS DE CAMAS");

        textHabitacionTipo.setText("TIPO HABITACIÓN");

        habitacionBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/search.png"))); // NOI18N
        habitacionBuscar.setText("BUSCAR");
        habitacionBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionBuscarActionPerformed(evt);
            }
        });

        habitacionTipoCama.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tipo de cama", "Cantidad "
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(habitacionTipoCama);

        habitacionGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/checked-1.png"))); // NOI18N
        habitacionGuardar.setText("GUARDAR");

        habitacionEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/pencil.png"))); // NOI18N
        habitacionEditar.setText("EDITAR");

        habitacionLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/escoba.png"))); // NOI18N
        habitacionLimpiar.setText("LIMPIAR");

        habitacionBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/vistas/resources/cancel.png"))); // NOI18N
        habitacionBorrar.setText("BORRAR");

        habitacionEstadoLibre.setSelected(true);
        habitacionEstadoLibre.setText("Libre");
        habitacionEstadoLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionEstadoLibreActionPerformed(evt);
            }
        });

        habitacionEstadoOcupada.setText("Ocupada");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(91, 91, 91)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textHabitacionTipo)
                                    .addComponent(textHabitacionId)
                                    .addComponent(textHabitacionTipoCama)
                                    .addComponent(textHabitacionEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(habitacionGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(habitacionEstadoLibre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(habitacionEstadoOcupada))
                            .addComponent(habitacionTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(habitacionEditar)
                                .addGap(64, 64, 64)
                                .addComponent(habitacionLimpiar))
                            .addComponent(habitacionId))
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(habitacionBorrar)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(habitacionBuscar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(textTitleDatosHabitacion)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(textTitleDatosHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitacionId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textHabitacionId)
                    .addComponent(habitacionBuscar))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textHabitacionTipo)
                    .addComponent(habitacionTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHabitacionTipoCama)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textHabitacionEstado)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(habitacionEstadoLibre)
                        .addComponent(habitacionEstadoOcupada)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(habitacionGuardar)
                    .addComponent(habitacionEditar)
                    .addComponent(habitacionLimpiar)
                    .addComponent(habitacionBorrar))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void habitacionIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitacionIdActionPerformed

    private void habitacionBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitacionBuscarActionPerformed

    private void habitacionEstadoLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionEstadoLibreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_habitacionEstadoLibreActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton habitacionBorrar;
    private javax.swing.JButton habitacionBuscar;
    private javax.swing.JButton habitacionEditar;
    private javax.swing.JRadioButton habitacionEstadoLibre;
    private javax.swing.JRadioButton habitacionEstadoOcupada;
    private javax.swing.JButton habitacionGuardar;
    private javax.swing.JTextField habitacionId;
    private javax.swing.JButton habitacionLimpiar;
    private javax.swing.JComboBox<String> habitacionTipo;
    private javax.swing.JTable habitacionTipoCama;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel textHabitacionEstado;
    private javax.swing.JLabel textHabitacionId;
    private javax.swing.JLabel textHabitacionTipo;
    private javax.swing.JLabel textHabitacionTipoCama;
    private javax.swing.JLabel textTitleDatosHabitacion;
    // End of variables declaration//GEN-END:variables
}
